import { products } from "./Products";

export const users = [
  {
    id: 1,
    firstName: "Dianne",
    lastName: "Russell",
    role: "Customer",
    // profileImage: "/images/avatars/dianne.jpg",
    billingAddress: {
      firstName: "Dainne",
      lastName: "Russell",
      street: "4140 Parker Rd.",
      city: "Allentown",
      state: "New Mexico",
      zipCode: "31134",
    },
    shippingAddress: {
      firstName: "Dainne",
      lastName: "Russell",
      street: "4140 Parker Rd.",
      city: "Allentown",
      state: "New Mexico",
      zipCode: "31134",
    },
    email: "dainne.ressell@gmail.com",
    phone: "(671) 555-0110",
    orderHistory: [
      {
        orderId: "#738",
        date: "8 Sep, 2026",
        subtotal: 100.0,
        discount: 0.2,
        shipping: "Free",
        total: 80.0,
        paymentMethod: "Paypal",
        productCount: 5,
        status: "Processing",
        billingAddress: {
          firstName: "Dainne",
          lastName: "Russell",
          street: "4140 Parker Rd.",
          city: "Allentown",
          state: "New Mexico",
          zipCode: "31134",
        },
        shippingAddress: {
          firstName: "Dainne",
          lastName: "Russell",
          street: "4140 Parker Rd.",
          city: "Allentown",
          state: "New Mexico",
          zipCode: "31134",
        },
        items: [
          { ...products[0], quantity: 1 },
          { ...products[1], quantity: 2 },
          { ...products[2], quantity: 3 },
          { ...products[3], quantity: 1 },
          { ...products[4], quantity: 1 },
        ],
      },
      {
        orderId: "#730",
        date: "12 Aug, 2026",
        total: 45.5,
        productCount: 2,
        status: "on the way",
      },
      {
        orderId: "#725",
        date: "03 Aug, 2026",
        total: 250.0,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#710",
        date: "15 Jul, 2026",
        total: 15.99,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#703",
        date: "24 May, 2026",
        total: 25.0,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#690",
        date: "10 Apr, 2026",
        total: 112.5,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#675",
        date: "22 Mar, 2026",
        total: 578.0,
        productCount: 13,
        status: "Completed",
      },
      {
        orderId: "#650",
        date: "05 Mar, 2026",
        total: 345.0,
        productCount: 7,
        status: "Completed",
      },
      {
        orderId: "#620",
        date: "14 Feb, 2026",
        total: 89.0,
        productCount: 2,
        status: "Returned",
      },
      {
        orderId: "#599",
        date: "29 Jan, 2026",
        total: 150.75,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#561",
        date: "1 Feb, 2025",
        total: 35.0,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#536",
        date: "21 Sep, 2025",
        total: 578.0,
        productCount: 13,
        status: "Completed",
      },
      {
        orderId: "#492",
        date: "22 Oct, 2025",
        total: 345.0,
        productCount: 7,
        status: "Completed",
      },
      {
        orderId: "#480",
        date: "15 Sep, 2025",
        total: 42.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#465",
        date: "01 Sep, 2025",
        total: 210.0,
        productCount: 5,
        status: "Completed",
      },
      {
        orderId: "#440",
        date: "12 Aug, 2025",
        total: 18.5,
        productCount: 1,
        status: "Cancelled",
      },
      {
        orderId: "#412",
        date: "30 Jul, 2025",
        total: 99.99,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#390",
        date: "15 Jun, 2025",
        total: 275.0,
        productCount: 8,
        status: "Completed",
      },
      {
        orderId: "#375",
        date: "28 May, 2025",
        total: 55.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#360",
        date: "10 May, 2025",
        total: 120.0,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#340",
        date: "22 Apr, 2025",
        total: 85.5,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#325",
        date: "05 Apr, 2025",
        total: 200.0,
        productCount: 6,
        status: "Completed",
      },
      {
        orderId: "#310",
        date: "15 Mar, 2025",
        total: 45.0,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#290",
        date: "28 Feb, 2025",
        total: 135.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#275",
        date: "10 Feb, 2025",
        total: 75.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#260",
        date: "25 Jan, 2025",
        total: 310.0,
        productCount: 9,
        status: "Completed",
      },
      {
        orderId: "#245",
        date: "12 Jan, 2025",
        total: 22.0,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#230",
        date: "05 Dec, 2024",
        total: 150.0,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#215",
        date: "20 Nov, 2024",
        total: 88.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#200",
        date: "05 Nov, 2024",
        total: 400.0,
        productCount: 12,
        status: "Completed",
      },
    ],
  },
  {
    id: 2,
    name: "Annette Black",
    role: "Customer",
    profileImage: "/images/avatars/annette.jpg",
    billingAddress: {
      fullName: "Annette Black",
      street: "1901 Thornridge Cir.",
      city: "Shiloh",
      state: "Hawaii",
      zipCode: "81063",
    },
    email: "annette.black@example.com",
    phone: "(239) 555-0108",
    orderHistory: [
      {
        orderId: "#821",
        date: "12 Nov, 2026",
        total: 45.0,
        productCount: 2,
        status: "Processing",
      },
      {
        orderId: "#805",
        date: "28 Oct, 2026",
        total: 12.5,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#790",
        date: "15 Sep, 2026",
        total: 210.0,
        productCount: 5,
        status: "Completed",
      },
      {
        orderId: "#775",
        date: "02 Sep, 2026",
        total: 85.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#760",
        date: "18 Aug, 2026",
        total: 150.0,
        productCount: 4,
        status: "Returned",
      },
      {
        orderId: "#745",
        date: "05 Aug, 2026",
        total: 55.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#730",
        date: "22 Jul, 2026",
        total: 320.0,
        productCount: 8,
        status: "Completed",
      },
      {
        orderId: "#710",
        date: "05 Jun, 2026",
        total: 120.5,
        productCount: 6,
        status: "Completed",
      },
      {
        orderId: "#695",
        date: "19 May, 2026",
        total: 45.0,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#680",
        date: "03 May, 2026",
        total: 180.0,
        productCount: 5,
        status: "Completed",
      },
      {
        orderId: "#665",
        date: "15 Apr, 2026",
        total: 95.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#650",
        date: "28 Mar, 2026",
        total: 210.0,
        productCount: 7,
        status: "Completed",
      },
      {
        orderId: "#635",
        date: "10 Mar, 2026",
        total: 35.0,
        productCount: 1,
        status: "Cancelled",
      },
      {
        orderId: "#620",
        date: "22 Feb, 2026",
        total: 145.0,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#605",
        date: "05 Feb, 2026",
        total: 75.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#590",
        date: "18 Jan, 2026",
        total: 250.0,
        productCount: 6,
        status: "Completed",
      },
    ],
  },
  {
    id: 3,
    name: "Cody Fisher",
    role: "Customer",
    profileImage: "/images/avatars/cody.jpg",
    billingAddress: {
      fullName: "Cody Fisher",
      street: "8502 Preston Rd.",
      city: "Inglewood",
      state: "Maine",
      zipCode: "98380",
    },
    email: "cody.fisher@example.com",
    phone: "(406) 555-0120",
    orderHistory: [
      {
        orderId: "#904",
        date: "01 Dec, 2026",
        total: 850.0,
        productCount: 15,
        status: "on the way",
      },
      {
        orderId: "#889",
        date: "15 Nov, 2026",
        total: 120.0,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#874",
        date: "28 Oct, 2026",
        total: 45.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#859",
        date: "12 Oct, 2026",
        total: 310.0,
        productCount: 7,
        status: "Completed",
      },
      {
        orderId: "#844",
        date: "25 Sep, 2026",
        total: 55.0,
        productCount: 2,
        status: "Returned",
      },
      {
        orderId: "#829",
        date: "10 Sep, 2026",
        total: 180.0,
        productCount: 5,
        status: "Completed",
      },
      {
        orderId: "#812",
        date: "15 Aug, 2026",
        total: 60.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#797",
        date: "28 Jul, 2026",
        total: 250.0,
        productCount: 8,
        status: "Completed",
      },
      {
        orderId: "#782",
        date: "12 Jul, 2026",
        total: 95.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#767",
        date: "25 Jun, 2026",
        total: 420.0,
        productCount: 11,
        status: "Completed",
      },
      {
        orderId: "#752",
        date: "10 Jun, 2026",
        total: 35.0,
        productCount: 1,
        status: "Cancelled",
      },
      {
        orderId: "#737",
        date: "28 May, 2026",
        total: 150.0,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#722",
        date: "12 May, 2026",
        total: 75.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#707",
        date: "25 Apr, 2026",
        total: 280.0,
        productCount: 7,
        status: "Completed",
      },
      {
        orderId: "#692",
        date: "10 Apr, 2026",
        total: 110.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#677",
        date: "28 Mar, 2026",
        total: 65.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#662",
        date: "12 Mar, 2026",
        total: 195.0,
        productCount: 6,
        status: "Completed",
      },
      {
        orderId: "#650",
        date: "10 Feb, 2026",
        total: 210.0,
        productCount: 8,
        status: "Completed",
      },
    ],
  },
  {
    id: 4,
    name: "Esther Howard",
    role: "Customer",
    profileImage: "/images/avatars/esther.jpg",
    billingAddress: {
      fullName: "Esther Howard",
      street: "3891 Ranchview Dr.",
      city: "Richardson",
      state: "California",
      zipCode: "62639",
    },
    email: "esther.howard@example.com",
    phone: "(316) 555-0116",
    orderHistory: [
      {
        orderId: "#955",
        date: "20 Dec, 2026",
        total: 45.0,
        productCount: 1,
        status: "Processing",
      },
      {
        orderId: "#940",
        date: "05 Dec, 2026",
        total: 125.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#925",
        date: "18 Nov, 2026",
        total: 80.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#910",
        date: "02 Nov, 2026",
        total: 210.0,
        productCount: 6,
        status: "Completed",
      },
      {
        orderId: "#895",
        date: "15 Oct, 2026",
        total: 55.0,
        productCount: 2,
        status: "Returned",
      },
      {
        orderId: "#880",
        date: "28 Sep, 2026",
        total: 340.0,
        productCount: 9,
        status: "Completed",
      },
      {
        orderId: "#865",
        date: "12 Sep, 2026",
        total: 95.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#850",
        date: "25 Aug, 2026",
        total: 180.0,
        productCount: 5,
        status: "Completed",
      },
      {
        orderId: "#835",
        date: "10 Aug, 2026",
        total: 45.0,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#820",
        date: "22 Jul, 2026",
        total: 275.0,
        productCount: 7,
        status: "Completed",
      },
      {
        orderId: "#805",
        date: "05 Jul, 2026",
        total: 110.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#790",
        date: "18 Jun, 2026",
        total: 65.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#775",
        date: "02 Jun, 2026",
        total: 195.0,
        productCount: 5,
        status: "Completed",
      },
      {
        orderId: "#760",
        date: "15 May, 2026",
        total: 85.0,
        productCount: 2,
        status: "Completed",
      },
    ],
  },
  {
    id: 5,
    name: "Jenny Wilson",
    role: "Customer",
    profileImage: "/images/avatars/jenny.jpg",
    billingAddress: {
      fullName: "Jenny Wilson",
      street: "6391 Elgin St.",
      city: "Celina",
      state: "Delaware",
      zipCode: "10299",
    },
    email: "jenny.wilson@example.com",
    phone: "(704) 555-0127",
    orderHistory: [
      {
        orderId: "#490",
        date: "15 Dec, 2026",
        total: 185.0,
        productCount: 5,
        status: "Processing",
      },
      {
        orderId: "#485",
        date: "02 Dec, 2026",
        total: 65.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#480",
        date: "18 Nov, 2026",
        total: 240.0,
        productCount: 7,
        status: "Completed",
      },
      {
        orderId: "#475",
        date: "05 Nov, 2026",
        total: 95.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#470",
        date: "22 Oct, 2026",
        total: 150.0,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#465",
        date: "08 Oct, 2026",
        total: 45.0,
        productCount: 1,
        status: "Returned",
      },
      {
        orderId: "#460",
        date: "25 Sep, 2026",
        total: 310.0,
        productCount: 8,
        status: "Completed",
      },
      {
        orderId: "#455",
        date: "12 Sep, 2026",
        total: 120.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#450",
        date: "28 Aug, 2026",
        total: 75.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#445",
        date: "15 Aug, 2026",
        total: 220.0,
        productCount: 6,
        status: "Completed",
      },
      {
        orderId: "#440",
        date: "02 Aug, 2026",
        total: 55.0,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#435",
        date: "18 Jul, 2026",
        total: 175.0,
        productCount: 5,
        status: "Completed",
      },
      {
        orderId: "#430",
        date: "05 Jul, 2026",
        total: 90.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#425",
        date: "22 Jun, 2026",
        total: 260.0,
        productCount: 7,
        status: "Completed",
      },
      {
        orderId: "#420",
        date: "08 Jun, 2026",
        total: 40.0,
        productCount: 1,
        status: "Cancelled",
      },
      {
        orderId: "#415",
        date: "25 May, 2026",
        total: 145.0,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#412",
        date: "14 Apr, 2026",
        total: 315.0,
        productCount: 9,
        status: "Completed",
      },
      {
        orderId: "#405",
        date: "28 Mar, 2026",
        total: 85.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#400",
        date: "15 Mar, 2026",
        total: 195.0,
        productCount: 5,
        status: "Completed",
      },
      {
        orderId: "#395",
        date: "02 Mar, 2026",
        total: 60.0,
        productCount: 2,
        status: "Completed",
      },
      {
        orderId: "#390",
        date: "18 Feb, 2026",
        total: 280.0,
        productCount: 8,
        status: "Completed",
      },
      {
        orderId: "#388",
        date: "02 Jan, 2026",
        total: 15.0,
        productCount: 1,
        status: "Completed",
      },
    ],
  },
];
