export const users = [
  {
    id: 1,
    name: "Dianne Russell",
    role: "Customer",
    avatar: "/images/avatars/dianne.jpg",
    billingAddress: {
      fullName: "Dainne Russell",
      street: "4140 Parker Rd.",
      city: "Allentown",
      state: "New Mexico",
      zipCode: "31134",
    },
    email: "dainne.ressell@gmail.com",
    phone: "(671) 555-0110",
    recentOrders: [
      {
        orderId: "#738",
        date: "8 Sep, 2020",
        total: 135.0,
        productCount: 5,
        status: "Processing",
      },
      {
        orderId: "#703",
        date: "24 May, 2020",
        total: 25.0,
        productCount: 1,
        status: "on the way",
      },
      {
        orderId: "#130",
        date: "22 Oct, 2020",
        total: 250.0,
        productCount: 4,
        status: "Completed",
      },
      {
        orderId: "#561",
        date: "1 Feb, 2020",
        total: 35.0,
        productCount: 1,
        status: "Completed",
      },
      {
        orderId: "#536",
        date: "21 Sep, 2020",
        total: 578.0,
        productCount: 13,
        status: "Completed",
      },
      {
        orderId: "#492",
        date: "22 Oct, 2020",
        total: 345.0,
        productCount: 7,
        status: "Completed",
      },
    ],
  },
  {
    id: 2,
    name: "Annette Black",
    role: "Customer",
    avatar: "/images/avatars/annette.jpg",
    billingAddress: {
      fullName: "Annette Black",
      street: "1901 Thornridge Cir.",
      city: "Shiloh",
      state: "Hawaii",
      zipCode: "81063",
    },
    email: "annette.black@example.com",
    phone: "(239) 555-0108",
    recentOrders: [
      {
        orderId: "#821",
        date: "12 Nov, 2020",
        total: 45.0,
        productCount: 2,
        status: "Processing",
      },
      {
        orderId: "#710",
        date: "05 Jun, 2020",
        total: 120.5,
        productCount: 6,
        status: "Completed",
      },
    ],
  },
  {
    id: 3,
    name: "Cody Fisher",
    role: "Customer",
    avatar: "/images/avatars/cody.jpg",
    billingAddress: {
      fullName: "Cody Fisher",
      street: "8502 Preston Rd.",
      city: "Inglewood",
      state: "Maine",
      zipCode: "98380",
    },
    email: "cody.fisher@example.com",
    phone: "(406) 555-0120",
    recentOrders: [
      {
        orderId: "#904",
        date: "01 Dec, 2020",
        total: 850.0,
        productCount: 15,
        status: "on the way",
      },
      {
        orderId: "#812",
        date: "15 Oct, 2020",
        total: 60.0,
        productCount: 3,
        status: "Completed",
      },
      {
        orderId: "#650",
        date: "10 Mar, 2020",
        total: 210.0,
        productCount: 8,
        status: "Completed",
      },
    ],
  },
  {
    id: 4,
    name: "Esther Howard",
    role: "Customer",
    avatar: "/images/avatars/esther.jpg",
    billingAddress: {
      fullName: "Esther Howard",
      street: "3891 Ranchview Dr.",
      city: "Richardson",
      state: "California",
      zipCode: "62639",
    },
    email: "esther.howard@example.com",
    phone: "(316) 555-0116",
    recentOrders: [
      {
        orderId: "#955",
        date: "20 Dec, 2020",
        total: 45.0,
        productCount: 1,
        status: "Processing",
      },
    ],
  },
  {
    id: 5,
    name: "Jenny Wilson",
    role: "Customer",
    avatar: "/images/avatars/jenny.jpg",
    billingAddress: {
      fullName: "Jenny Wilson",
      street: "6391 Elgin St.",
      city: "Celina",
      state: "Delaware",
      zipCode: "10299",
    },
    email: "jenny.wilson@example.com",
    phone: "(704) 555-0127",
    recentOrders: [
      {
        orderId: "#412",
        date: "14 Jan, 2020",
        total: 315.0,
        productCount: 9,
        status: "Completed",
      },
      {
        orderId: "#388",
        date: "02 Jan, 2020",
        total: 15.0,
        productCount: 1,
        status: "Completed",
      },
    ],
  },
];
